# Stubs for groveco_challenge.cli (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .finder import StoreFinder
from typing import Any, Optional

CONTEXT_SETTINGS: Any

def cli(zipcode: Optional[str], address: Optional[str], units: str, output: str, results: int, max_workers: int, actual: bool) -> Any: ...
